Added files from Microverse Admission Trial Project
AduwuJoseph/Microverse-admission-trial-project-review pull request #1
Opened 2022-07-04 15:39 UTC by AduwuJoseph

The branch is created from the Microverse Admission Collaboration trial project. Here is how i achieve this:

- Created this repository and copy the collaboration trial project without modification
- Created a branch, commit and push for review purpose

2022-07-04 15:56 UTC, AduwuJoseph reviewed
Great work so far!
Meanwhile, i will recommend you take not of the following for correction and changes:

- The work does not have a README.md: It is important that every of your repository have a README.md to give the viewer an overview of what your repository is all about. Your README.md should also tell us how to set it up locally and deploy it. The technologies used in writing the code, authors and contributors (if there is any).

2022-07-04 16:17 UTC, AduwuJoseph reviewed
Reviewing your index.html page, the following are observed:

- html element attribute "id" should only be used when the **id** is only appearing once in a web page. For example: instead of using id for (id="features_container"), class attribute would have been ideal for the case i.e. class="features_container"

2022-07-04 16:24 UTC, danmainah requested changes
Hi @AduwuJoseph, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design
✔️  Good use of simple language

# Required Changes ♻️

- [ ] Kindly ensure you add inline comments in your review, also ensure your comment are polite by using words like please and pinpoint the sections the error is in.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-05 13:16 UTC, youmari requested changes
Hi @AduwuJoseph , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️Writing a review  

 ## Required Changes ♻️
 

- [ ] as the previous reviewer asked you should give a review using the [inline comments](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) which show the block of code you requested change to  I leave with a link to see how you can  use GitHub inline comments 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 13:47 UTC, AduwuJoseph reviewed
Please check the comment below and make required changes

2022-07-05 13:47 UTC, AduwuJoseph commented on index.html
> +            </div>
Good job so far with your CSS!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design
✔️  Good use of html semantics

# Required Changes ♻️

- [ ] Kindly ensure you change the id="features_container" to class="features_container" as the attribute class is more ideal for a situation where an attribute is not unique for a page. id attribute should be used only when you are sure the id will not occur more than once in a code

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.title h3{
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +#features__container .features__content p {
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +#features__container .features__content {
- [] Kindly ensure you add a new line here too

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.form form button:hover {
- [] Kindly ensure you add a new line here too

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.form form button {
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +body {
Good job so far with your CSS!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design
✔️  Good use of css semantics

# Required Changes ♻️

- [ ] Kindly ensure you add a new line between line 84 and line 85 (standard css practice advises a new line after every block)

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.navbar .navbar__brand img {
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.navbar .navbar__links ul li a {
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 13:47 UTC, AduwuJoseph commented on index.css
> +.form {
- [ ] Kindly ensure you add a new line here too. An empty new line after each css block

2022-07-05 14:21 UTC, omarsalem7 approved these changes
Hi @AduwuJoseph 😊, 

# STATUS: APPROVED! 🥇 💯 

![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
- Descriptive pull request ✔️
- Good descriptive readme ✔️
- No linter errors ✔️

Cheers and Happy coding!👏👏👏

## Optional suggestions

- [ ] Instead of adding a comment for every line of code, you can just say `please add one empty line after each block in your code to make it clear and readable` and also add a reason why you request these changes.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 14:24 UTC, merged